In [4]:
import numpy as np
import matplotlib.pyplot
import nnfs
from nnfs.datasets import spiral_data

# Chapter 4

## Activation Functions

### ReLU

In [ ]:
#Relu Activation
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0,inputs)

In [ ]:
#dense layer from Chapter 3
class Layer_Dense: #Completely Random Dense Layer
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons) #initialize weights
        #Note: Multiplied by 0.01 since it is often better to have start weights that minimally affect the training
        self.biases = np.zeros((1, n_neurons)) # initialize biases to 0
        #Note: initial bias for 0 is common to ensure neuron fires 
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
    

In [ ]:
#Data from chapter 3
nnfs.init()
X, y = spiral_data(samples=100, classes=3)
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense1.forward(X)
activation1.forward(dense1.output)


print(activation1.output[:5])

[[0.         0.         0.        ]
 [0.         0.00011395 0.        ]
 [0.         0.00031729 0.        ]
 [0.         0.00052666 0.        ]
 [0.         0.00071401 0.        ]]


### Softmax

In [11]:
class Activation_Softmax:
    def forward(self, inputs):
        #Get unnormalized probabilities
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims = True))
        # Normalize them for each sample
        probabilites = exp_values / np.sum(exp_values, axis = 1, keepdims=True)
        
        self.output = probabilites

In [ ]:
#Data from chapter 3
nnfs.init()
X, y = spiral_data(samples=100, classes=3)
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()
dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
