In [ ]:
import numpy as np
import matplotlib.pyplot as plt


# Charper 2: Coding Our First Neurons

### A single Neuron

In [20]:
inputs = [1,2,3]
weights = [0.2, 0.8, -0.5] #start with static weights, will be tuned later
bias = 2 #start with static bias, will be tuned later

output = np.dot(weights, inputs)+bias
    
print(output)

2.3


### A layer of Neurons 

In [23]:
inputs = [1,2,3,2.5]
# Weights still static for this example
weights = []
weights.append([0.2,0.8,-0.5,1]) #First Node
weights.append([0.5, -0.91, 0.26, -0.5]) #Second Node
weights.append([-0.26, -0.27, 0.17, 0.87]) #Third Node

#Bias still static for this example
biases = [2,3,0.5]

#Calculate
layer_outputs = np.dot(weights, inputs) + biases
    
print (layer_outputs)


[4.8   1.21  2.385]


### A Layer of Neurons & Batch of Data 

In [37]:
inputs = [[1,2,3,2.5],
          [2,5,-1,2],
          [-1.5,2.7,3.3,-0.8]]
weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26, -0.27, 0.17,0.87]]
biases = [2,3,0.5]

layer_outputs = np.dot(inputs, np.array(weights).T) + biases

print(layer_outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
